# Generated by Django 4.1.7 on 2023-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=80)),
            ],
        ),
    ]
